import numpy as np
import pandas as pd


class Var:
    """
    The class serves as an abstract base class, designed to establish a standardised, cohesive 
    framework for Value-at-Risk (VaR) calculations. This foundational class integrates the core 
    computational components of the risk model by combining the portfolio definition, 
    the underlying copula specification, and the empirical market data required to construct 
    marginal distributions. 
    """

    def __init__(self, calibration, spot, copula, portfolio):
        self.calibration = calibration
        self.spot = spot
        self.copula = copula
        self.portfolio = portfolio
        self.pnls = None
        self.name = 'Not implemented'

    def calculate_pnls(self):
        raise NotImplementedError

    def get_quantile(self, quantile):
        return np.quantile(self.pnls, quantile)
    
    def get_port_value(self):
        return self.spot.dot(self.portfolio.T)


class VarSim(Var):
    """
    Although VarSim is currently the sole concrete child class implemented within this project, 
    the object-oriented architecture is inherently extensible, deliberately leaving room to 
    seamlessly incorporate alternative models and methodologies in future research. In its 
    execution, processes output scenarios generated by the copula, which manifest as uniformly
    distributed coordinate vectors situated within a d-dimensional hypercube [0, 1]^d. 
    To translate these theoretical, uniform probabilities into realistic market conditions, 
    the system maps them against the market data serving as the marginal distribution for each
    individual stock. This transformation is executed utilizing the "quantile" function 
    (effectively the inverse cumulative distribution function) provided by the NumPy package. 
    During this step, the model explicitly relies on the standard assumption of log-normality, 
    which is widely accepted convention for modeling the behavior of equity returns. Once a 
    simulated vector of individual asset returns is generated, it is multiplied with the portfolio
    weights to calculate the aggregated return of the entire portfolio. To ensure statistical 
    robustness and accurately capture a wide spectrum of potential market movements, this exact
    procedure is iterated 10,000 times (i.e. number of Monte-Carlo simulations). Such sampling 
    effectively constructs a probability distribution of the overall portfolio returns, from 
    which specified VaR metrics can be extracted (e.g. 75th, 90th, 99th and 99.5th percentiles).
    """

    def __init__(self, calibration, spot, copula, portfolio, method='linear'):
        Var.__init__(self, calibration, spot, copula, portfolio)
        self.name =f'VaR - Empirical marginals ({method}) - {self.copula.name}'
        self.method = method

    def calculate_pnls(self, numb_scen):
        joint_sim = self.copula.get_sims(numb_scen)
        #joint_sim.to_csv(f'C:\\Temp\\joint_sim.csv')
        #self.spot.to_csv(f'C:\\Temp\\spot.csv')
        #joint_sim.to_csv(f'C:\\Temp\\sims.csv')

        joint_sim[joint_sim > 0.9999] = 0.9999
        joint_sim[joint_sim < 0.0001] = 0.0001
        joint_sim = joint_sim.fillna(0.5)
        print(f'=> min:{joint_sim.min().min()}, max:{joint_sim.max().max()}')

        #todo: only log normal
        scen = pd.DataFrame(
            data=np.array([(np.exp(np.quantile(self.calibration[x], joint_sim[x], method=self.method))-1.0)*self.spot[x] for x in self.calibration.columns ]).T, 
            columns=self.calibration.columns)
        #scen.to_csv(f'C:\\Temp\\scen.csv')
        print(f'Simulation stats, non nones count: {sum(list(scen.count()))}, needs {scen.size}')
        self.pnls = scen.dot(self.portfolio.T)
         



